# Tratamento

---

#### pela Importação e tratamento da nossa base de dados

## Etapas feitas no código abaixo: 

- Importação do arquivo
- Traduzindo colunas para o português
- Tranformando algumas colunas para o tipo categoria
- Criando faixa etária de idade para ajuda na análise
- Classificando tempo de empresa em categorias
- Razão salarial | salário do funcionário / média do cargo
- Satisfação geral no trabalho vs Pedidos de demissão
- Clasificando distância do trabalho
- Reordenando ordem das colunas
- Salvando nossa base em um novo arquivo csv
---

# Código:

- Importação do arquivo

In [83]:
import pandas as pd

df = pd.read_csv("../data/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

- Traduzindo colunas para o português

In [84]:
# Criadnoo dicionário de tradução das colunas
colunas_traduzidas = {
    'Age': 'Idade',
    'Attrition': 'Demitido',  # Ou 'Demissao', 'Evasao'
    'BusinessTravel': 'Viagens_a_Negocio',
    'DailyRate': 'Valor_Diaria',
    'Department': 'Departamento',
    'DistanceFromHome': 'Distancia_de_Casa',
    'Education': 'Escolaridade',
    'EducationField': 'Area_de_Formacao',
    'EmployeeCount': 'Contagem_de_Funcionarios',
    'EmployeeNumber': 'ID_Funcionario',
    'EnvironmentSatisfaction': 'Satisfacao_com_Ambiente',
    'Gender': 'Genero',
    'HourlyRate': 'Valor_Hora',
    'JobInvolvement': 'Envolvimento_com_Trabalho',
    'JobLevel': 'Nivel_do_Cargo',
    'JobRole': 'Cargo',
    'JobSatisfaction': 'Satisfacao_com_Trabalho',
    'MaritalStatus': 'Estado_Civil',
    'MonthlyIncome': 'Renda_Mensal',
    'MonthlyRate': 'Valor_Mensal',
    'NumCompaniesWorked': 'Numero_de_Empresas_Anteriores',
    'Over18': 'Maior_de_18',
    'OverTime': 'Hora_Extra',
    'PercentSalaryHike': 'Percentual_Aumento_Salario',
    'PerformanceRating': 'Avaliacao_Desempenho',
    'RelationshipSatisfaction': 'Satisfacao_Relacionamento',
    'StandardHours': 'Horas_Padrao',
    'Nivel_Stock_Options': 'Nivel_Stock_Options',  # Opções de ações da empresa
    'TotalWorkingYears': 'Total_Anos_Trabalhados',
    'TrainingTimesLastYear': 'Treinamentos_Ano_Passado',
    'WorkLifeBalance': 'Equilibrio_Vida_Trabalho',
    'YearsAtCompany': 'Anos_na_Empresa',
    'YearsInCurrentRole': 'Anos_no_Cargo_Atual',
    'YearsSinceLastPromotion': 'Anos_Desde_Ultima_Promocao',
    'YearsWithCurrManager': 'Anos_com_Gerente_Atual'
}

# Aplicando a tradução no DataFrame
df = df.rename(columns=colunas_traduzidas)

df.head()

,Idade,Demitido,Viagens_a_Negocio,Valor_Diaria,Departamento,Distancia_de_Casa,Escolaridade,Area_de_Formacao,Contagem_de_Funcionarios,ID_Funcionario,...,Satisfacao_Relacionamento,Horas_Padrao,StockOptionLevel,Total_Anos_Trabalhados,Treinamentos_Ano_Passado,Equilibrio_Vida_Trabalho,Anos_na_Empresa,Anos_no_Cargo_Atual,Anos_Desde_Ultima_Promocao,Anos_com_Gerente_Atual
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

- Tranformando algumas colunas para o tipo categoria

In [85]:
colunas_categoricas = [ 
    "Demitido",
    "Genero",
    "Estado_Civil",
    "Cargo",
    "Departamento",
    "Area_de_Formacao",
    "Viagens_a_Negocio"
]

df[colunas_categoricas] = df[colunas_categoricas].astype("category")

- Criando faixa etária de idade para ajuda na análise

In [86]:
df["Faixa_Etaria"] = df["Idade"].apply(
    lambda x: "Jovem" if 18 <= x <= 29
    else "Adulto" if 30 <= x <= 44
    else "Maduro" if 45 <= x <= 59
    else "Idoso"
)

# mandante['pontos'] = mandante.apply(
#    # Calculando ponntuação
#    lambda x: 3 if x['gols_pro'] > x['gols_contra']
#    else 1 if x['gols_pro'] == x['gols_contra']
#    else 0,
#    axis=1

# | Faixa Etária    | Classificação |
# | --------------- | ------------- |
# | 18 a 29 anos    | Jovem         |
# | 30 a 44 anos    | Adulto        |
# | 45 a 59 anos    | Maduro        |
# | 60 anos ou mais | Idoso         |

- Classificando tempo de empresa em categorias

In [87]:
df["Faixa_de_tempo_empresa"] = df["Anos_na_Empresa"].apply(
    lambda x: "Recém contratado" if 0 <= x <= 1
    else "Inicio de carreira" if 2 <= x <= 4
    else "Funcionário estabelecido" if 5 <= x <= 9
    else "Experiente" if 10 <= x <= 14
    else "Muito experiente" if 15 <= x <= 19
    else "Veterano"
)
# Faixa	Interpretação

# 0–1 ano	    Recém-contratados
# 2–4 anos	    Início de carreira
# 5–9 anos	    Funcionários estabelecidos
# 10–14 anos    Experientes
# 15–19 anos    Muito experientes
# 20+ anos	    Veteranos

- Razão salarial | salário do funcionário / média do cargo

In [88]:
df["Razão_salarial"] = df["Renda_Mensal"].mean() / df["Renda_Mensal"]

- Satisfação geral no trabalho vs Pedidos de demissão

In [89]:
df["Satisfação_geral"] = df["Satisfacao_com_Ambiente"] + df["Satisfacao_com_Trabalho"] + df["Satisfacao_Relacionamento"] + df["Equilibrio_Vida_Trabalho"]

- Clasificando distância do trabalho

In [90]:
df["Distancia_de_Casa"].min()
df["Distancia_de_Casa"].max()

np.int64(29)

In [91]:
df["Faixa_Distancia_de_Casa"] = df["Distancia_de_Casa"].apply(
    lambda x: "Muito próxima" if 0 <= x <= 5
    else "Próxima" if 6 <= x <= 10
    else "Moderada" if 11 <= x <= 15
    else "Distante" if 16 <= x <= 20
    else "Muito distantew"
)

# Distância	Categoria
# 1–5	Muito próxima
# 6–10	Próxima
# 11–15	Moderada
# 16–20	Distante
# 21–29	Muito distante

- Reordenando ordem das colunas

In [92]:
colunas_ordenadas = [
    # Identificação
    "ID_Funcionario",
    "Demitido",

    # Perfil pessoal
    "Idade",
    "Faixa_Etaria",
    "Genero",
    "Estado_Civil",
    "Maior_de_18",
    "Distancia_de_Casa",
    "Faixa_Distancia_de_Casa",

    # Educação
    "Escolaridade",
    "Area_de_Formacao",

    # Estrutura organizacional
    "Departamento",
    "Cargo",
    "Nivel_do_Cargo",

    # Remuneração
    "Renda_Mensal",
    "Razão_salarial",
    "Percentual_Aumento_Salario",
    "StockOptionLevel",
    "Valor_Hora",
    "Valor_Diaria",
    "Valor_Mensal",

    # Trabalho e desempenho
    "Hora_Extra",
    "Viagens_a_Negocio",
    "Envolvimento_com_Trabalho",
    "Avaliacao_Desempenho",
    "Treinamentos_Ano_Passado",

    # Satisfação e clima
    "Satisfacao_com_Ambiente",
    "Satisfacao_com_Trabalho",
    "Satisfacao_Relacionamento",
    "Equilibrio_Vida_Trabalho",
    "Satisfação_geral",

    # Histórico profissional
    "Numero_de_Empresas_Anteriores",
    "Total_Anos_Trabalhados",

    # Tempo na empresa
    "Anos_na_Empresa",
    "Faixa_de_tempo_empresa",
    "Anos_no_Cargo_Atual",
    "Anos_Desde_Ultima_Promocao",
    "Anos_com_Gerente_Atual",

    # Colunas técnicas/constantes
    "Contagem_de_Funcionarios",
    "Horas_Padrao"
]

df = df[colunas_ordenadas]

- Salvando nossa base em um novo arquivo csv

In [93]:
# Criando um novo arquivo CSV com as colunas traduzidas
df.to_csv("../data/tabela_base_traduzida.csv", index=False)

In [94]:
# Análise exploratória dos dados

df = pd.read_csv("../data/tabela_base_traduzida.csv")

df.shape

(1470, 40)